uploads = []
generated = []

[[outputs]]
id = "yjMXzPE4pe-F3aBBfAJlV"
uri = "file://client/public/logo-512.png"
type = "image"
title = "512×512 logo (high resolution)"

[[outputs]]
id = "sL_vKZcZbljCWSIqtygH2"
uri = "file://client/public/android-chrome-192x192.png"
type = "image"
title = "192×192 logo (for AdSense upload)"
